# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_users', models.CharField(max_length=200)),
                ('a_conversions', models.CharField(max_length=200)),
                ('b_users', models.CharField(max_length=200)),
                ('b_conversions', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
