# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
