# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_test_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='created_by',
        ),
    ]
